config/routes.rb
Rails.application.routes.draw do

  get '/carrito', to: 'payments#carrito'
  get '/compras', to: 'payments#compras'
  get 'payments/express'
  get 'transactions/checkout'
  resources :attachments
  resources :payments
  resources :posts

  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                                          registrations: "registrations"}

  resources :usuario
  get 'welcome/index'
  post 'usuario/follow'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  include Picturable  # Concern Picturable para permitir subir imágenes
  #include Trackable # Concern Trackable para permitir trackear las acciones de los usuarios

  belongs_to :usuario, dependent: :destroy
  has_many :attachments
  has_many :payments
  validates :titulo, presence: true, uniqueness: true
  before_save :valores_por_default

  # Registrará cada vez que se cree, actualice o elimine un post
  include PublicActivity::Model
  tracked owner: Proc.new { |controller,model| controller.current_usuario }
  #after_create {|post| post.message 'create'}

  # def message action
  #  msg = {
  #     resource: 'posts',
  #     action: action,
  #     id: self.id,
  #     obj: self,
  #     username: self.usuario.username.capitalize,
  #     user_id: self.usuario.id

  #  }
  #   $redis.publish 'rt-change', msg.to_json
  # end

  def valores_por_default
    self.costo ||= 0 # asigna 0 cuando no tenga un valor
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # authenticate es un helper de Devise, luego se añade el nombre del modelo
  # Solo los usuarios no loggeados podran ejecutar show e index
  before_action :authenticate_usuario!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_usuario.posts.new(post_params)
    # @post = Post.new(post_params)
    # @post.usuario = current_usuario

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :contenido, :archivo, :costo)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :archivo %><br>
    <%= f.file_field :archivo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :costo %><br>
    <%= f.number_field :costo, class: "form-control", step: "any" %>
  </div>
  <div id="wysi-toolbar"></div>
  <div class="form-group">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Publicar", class: "btn btn-info" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<ul class="list-group">
  <% @posts.each do | post | %>
    <li class="list-group-item">
      <%= link_to post.titulo, post %>
    </li>
  <% end %>
</ul>

<% if usuario_signed_in? %>
  <%= link_to 'New Post', new_post_path, class: "btn btn-info" %>
<% end %>
<br><br>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 center-block no-float">
      <h1>Nuevo Post</h1>
      <%= render 'form' %>

      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="jumbotron">
  <h1><%= @post.titulo %></h1>
  <div>
    <%= @post.contenido %>
  </div>
  <% if usuario_signed_in? %>

     <!-- la varible payment: es la que se pasa como parametro al form_for del form.html.erb
      y crea un nuevo pago vacio. La variable post: es la misma desde la que se está haciendo
      el render del parcial form.html.erb y su valor es el del hidden_field post.id -->
    <%= render "payments/form", payment: Payment.new, post: @post  %>
  <% end %>
</div>

<div class="text-right">
  <% if @post.usuario and usuario_signed_in? and @post.usuario.id == current_usuario.id %>

      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Eliminar', @post, method: :delete,  data: { confirm: "¿Seguro que quieres borrarlo?"} %> |
   <% end %>
    <%= link_to 'Back', posts_path %>
</div>