config/routes.rb
Rails.application.routes.draw do

  get '/carrito', to: 'payments#carrito'
  get '/compras', to: 'payments#compras'
  get 'payments/express'
  get 'transactions/checkout'
  resources :attachments
  resources :payments
  resources :posts

  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                                          registrations: "registrations"}

  resources :usuario
  get 'welcome/index'
  post 'usuario/follow'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyDesign</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice" style="<%= "display:none;" if alert.nil? %>"><%= notice %></p>
    <p class="alert" style="<%= "display:none;" if alert.nil? %>"><%= alert %></p>
  <header>
    <nav>
      <ul class="nav nav-tabs">
        <li>
          <%= link_to "Inicio", root_path %>
        </li>
        <li>
          <%= link_to "Posts", posts_path %>
        </li>
        <% if usuario_signed_in? %>
          <li>
            <%= link_to "Mi carrito", carrito_path %>
          </li>
          <li>
            <%= link_to "Mis compras", compras_path %>
          </li>
          <li>
            <%= link_to "Editar Pefil", edit_usuario_registration_path(current_usuario) %>
          </li>
          <li>
            <%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to "Mi perfil", current_usuario %>
          </li>
        <% else %>
          <li>
            <%= link_to "Ingresar", new_usuario_session_path %>
          </li>
          <li>
            <%= link_to "Registrarse", new_usuario_registration_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </header>
    <div class="container">
      <div class="row">
          <div class="col-md-6 center-block no-float">
            <%= yield %>
          </div>
      </div>
    </div>
</body>
</html>